name: My first example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message
              run: echo "This my first message"

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   sudo apt-get install -y cowsay
                   echo "This is sai"

            - name: Generate ASCII Artwork
              run: |
                   cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                   cat dragon.txt

            - name: Execute shell script
              run: |
                   chmod +x .github/workflows/sai.sh
                   ./.github/workflows/sai.sh

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: This is second
              run: sleep 30
    
    third_job:
        runs-on: ubuntu-latest
        steps:
            - name: This is third
              run: sleep 35


            
              


