name: My first example

on: push

env: 
    NAME_NAME1: sai
    DOCKER_PASS: yogendar@123
jobs:
    first_job:
        env: 
            NAME_NAME: sai
            NAME: saisai
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   sudo apt-get install -y cowsay

            - name: Generate ASCII Artwork
              run: |
                   cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                   cat dragon.txt

            - name: Upload Artifactes
              uses: actions/upload-artifact@v4
              with:
                   name: dragon text file
                   path: dragon.txt

            - name: Execute shell script
              run: |
                   env | grep NAME
                   echo "This is ${{ secrets.DOCKER_PASS }}" >> sai.txt
                   cat sai.txt

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
          - name: Download Artifacte
            uses: actions/download-artifact@v4
            with:
                 name: dragon text file
          - name: Dragon file display
            run: cat dragon.txt
    

    

            
              


