name: My first example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message
              run: echo "This my first message"

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   ls -al
                   echo "This is sai"

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt