name: My first example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "This my first message"

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   ls -al
            
            - name: Update packages
              run: sudo apt update -y

            - name: executing shell script
              run: ./sai.sh
            