name: My first example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "This my first message"

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   ls -al

            - name: executing shell script
              run: echo "This is sai"
            