name: My first example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message
              run: echo "This my first message"

            - name: Files Lists
              run: |
                   ls
                   ls -altr
                   sudo apt-get install -y cowsay
                   echo "This is sai"

            - name: Generate ASCII Artwork
              run: |
                   cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                   cat dragon.txt

            - name: Upload Artifactes
              uses: actions/upload-artifact@v4
              with:
                   name: dragon text file
                   path: dragon.txt

            - name: Execute shell script
              run: |
                   chmod +x .github/workflows/sai.sh
                   ./.github/workflows/sai.sh

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
          - name: Download Artifacte
            uses: actions/download-artifact@v4
            with:
                 name: dragon text file
          - name: Dragon file display
            run: cat dragon.txt
    

    

            
              


